package Models;
// Generated 04-feb-2019 19:46:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * XCsModel generated by hbm2java
 */
public class XCsModel  implements java.io.Serializable {


     private int id;
     private XDireccionModel XDireccionModel;
     private String telefono;
     private String name;
     private Set XDependienteModels = new HashSet(0);

    public XCsModel() {
    }

	
    public XCsModel(int id, XDireccionModel XDireccionModel, String telefono) {
        this.id = id;
        this.XDireccionModel = XDireccionModel;
        this.telefono = telefono;
    }
    public XCsModel(int id, XDireccionModel XDireccionModel, String telefono, Integer createUid, Date createDate, Integer writeUid, Date writeDate, String name, Set XDependienteModels) {
       this.id = id;
       this.XDireccionModel = XDireccionModel;
       this.telefono = telefono;
       this.name = name;
       this.XDependienteModels = XDependienteModels;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public XDireccionModel getXDireccionModel() {
        return this.XDireccionModel;
    }
    
    public void setXDireccionModel(XDireccionModel XDireccionModel) {
        this.XDireccionModel = XDireccionModel;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getXDependienteModels() {
        return this.XDependienteModels;
    }
    
    public void setXDependienteModels(Set XDependienteModels) {
        this.XDependienteModels = XDependienteModels;
    }

    @Override
    public String toString() {
        return name;
    }
}