package Models;
// Generated 04-feb-2019 19:46:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * XHistmedicoModel generated by hbm2java
 */
public class XHistmedicoModel  implements java.io.Serializable {


     private int id;
     private XDependienteModel XDependienteModel;
     private String name;
     private String descripcion;

    public XHistmedicoModel() {
    }

	
    public XHistmedicoModel(int id, XDependienteModel XDependienteModel) {
        this.id = id;
        this.XDependienteModel = XDependienteModel;
    }
    public XHistmedicoModel(int id, XDependienteModel XDependienteModel, String name, String descripcion, Integer createUid, Date createDate, Integer writeUid, Date writeDate) {
       this.id = id;
       this.XDependienteModel = XDependienteModel;
       this.name = name;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public XDependienteModel getXDependienteModel() {
        return this.XDependienteModel;
    }
    
    public void setXDependienteModel(XDependienteModel XDependienteModel) {
        this.XDependienteModel = XDependienteModel;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public String toString() {
        return "XHistmedicoModel{" + "id=" + id + ", XDependienteModel=" + XDependienteModel + ", name=" + name + ", descripcion=" + descripcion + '}';
    }




}


