package Models;
// Generated 04-feb-2019 19:46:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * XLlamadaModel generated by hbm2java
 */
public class XLlamadaModel  implements java.io.Serializable {


     private int id;
     private XAsistenteModel XAsistenteModel;
     private XAvisoModel XAvisoModel;
     private XDependienteModel XDependienteModel;
     private Date fechaHora;

    public XLlamadaModel() {
    }

	
    public XLlamadaModel(int id, XAsistenteModel XAsistenteModel, XAvisoModel XAvisoModel, XDependienteModel XDependienteModel) {
        this.id = id;
        this.XAsistenteModel = XAsistenteModel;
        this.XAvisoModel = XAvisoModel;
        this.XDependienteModel = XDependienteModel;
    }
    public XLlamadaModel(int id, XAsistenteModel XAsistenteModel, XAvisoModel XAvisoModel, XDependienteModel XDependienteModel, Date fechaHora, Integer createUid, Date createDate, Integer writeUid, Date writeDate) {
       this.id = id;
       this.XAsistenteModel = XAsistenteModel;
       this.XAvisoModel = XAvisoModel;
       this.XDependienteModel = XDependienteModel;
       this.fechaHora = fechaHora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public XAsistenteModel getXAsistenteModel() {
        return this.XAsistenteModel;
    }
    
    public void setXAsistenteModel(XAsistenteModel XAsistenteModel) {
        this.XAsistenteModel = XAsistenteModel;
    }
    public XAvisoModel getXAvisoModel() {
        return this.XAvisoModel;
    }
    
    public void setXAvisoModel(XAvisoModel XAvisoModel) {
        this.XAvisoModel = XAvisoModel;
    }
    public XDependienteModel getXDependienteModel() {
        return this.XDependienteModel;
    }
    
    public void setXDependienteModel(XDependienteModel XDependienteModel) {
        this.XDependienteModel = XDependienteModel;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }

    @Override
    public String toString() {
        return "XLlamadaModel{" + "id=" + id + ", XAsistenteModel=" + XAsistenteModel + ", XAvisoModel=" + XAvisoModel + ", XDependienteModel=" + XDependienteModel + ", fechaHora=" + fechaHora + '}';
    }




}


