package Models;
// Generated 04-feb-2019 19:46:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * XRecursocomModel generated by hbm2java
 */
public class XRecursocomModel  implements java.io.Serializable {


     private int id;
     private String name;
     private String descripcion;
     private Set XOfrecerrcModels = new HashSet(0);

    public XRecursocomModel() {
    }

	
    public XRecursocomModel(int id) {
        this.id = id;
    }
    public XRecursocomModel(int id, String name, String descripcion, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set XOfrecerrcModels) {
       this.id = id;
       this.name = name;
       this.descripcion = descripcion;
       this.XOfrecerrcModels = XOfrecerrcModels;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getXOfrecerrcModels() {
        return this.XOfrecerrcModels;
    }
    
    public void setXOfrecerrcModels(Set XOfrecerrcModels) {
        this.XOfrecerrcModels = XOfrecerrcModels;
    }

    @Override
    public String toString() {
        return "XRecursocomModel{" + "id=" + id + ", name=" + name + ", descripcion=" + descripcion + ", XOfrecerrcModels=" + XOfrecerrcModels + '}';
    }




}


